name: CI to Zendesk Dockerhub

on:
  push:
    tags:
      - v*.*.*

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: zendesk/checkout@v2
        with:
          fetch-depth: '1'
      - name: Set up QEMU
        run: |-
          QEMU_IMAGE=tonistiigi/binfmt:latest
          docker pull $QEMU_IMAGE
          docker image inspect $QEMU_IMAGE
          docker run --rm --privileged $QEMU_IMAGE --install all
      - name: Set up Docker Buildx
        id: buildx
        uses: zendesk/setup-buildx-action@v1.6.0
        with:
          install: true
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Docker Build and push
        run: |-
          current_tag=zendesk/maxwell:"${GITHUB_REF##refs/tags/}"
          latest_tag=zendesk/maxwell:latest
          docker buildx build --platform=linux/arm64,linux/amd64 --file=Dockerfile --push --tag="$current_tag" --tag="$latest_tag" .
